Timeseries
enercoop/enda pull request #15
Opened 2024-02-16 15:50 UTC by ClementJeannesson

Made TimeSeries more robust: 
- sepeartion between TimeSeries and Resample classes
- improvment of decorators 
- depreciation of old TimeSeries functions

2024-02-21 11:03 UTC, sylviodupin requested changes
Quelques commentaires mais au global trop cool, les nouvelles fonction dans timeseries sont trop bien.
Quelques remarques :
- j'ai pas mal de petites erreurs de linter qui traînent (genre des else en trop, des .keys() pas utiles ...)
- Il manque black sur la majorité des fichiers
- Il n'y a pas de docstrings dans les tests unitaires : on avait dit qu'on devait en mettre, mais pas sûr que ce soit très utile en pratique

2024-02-22 14:21 UTC, ClementJeannesson commented on enda/decorators.py
> +
C'est bien ça. 
Je conçois la remarque, dans le sens où on ne checke jamais si la donnée d'entrée est un dataframe. 

En revanche, en pratique, je pense que c'est plus souple de ne pas forcer le nom de l'argument 'dataframe' (par exemple 'df') de la fonction décorée, et pas forcément gênant en pratique, parce que l'appel au décorateur se fait au moment où on développe une fonction, et pas au moment où on l'appelle (et on peut raisonnablement penser qu'un développeur sait ce qu'il fait s'il décide de décorer la fonction). 

En gros, par rapport à avant, si on décore une fonction, on est obligé de donner un argument au décorateur, eg:
```python
@handle_multiindex(arg_name='timeseries_df')
def function(timeseries_df: pd.Dataframe, *args, **kwargs): 
...
```

Du coup, le nom de l'argument est passé en dur lors du développement de la fonction, et a priori, c'est un dataframe...

Pour rendre plus résilient le fonctionnement, deux choses qu'on peut faire: 
- supprimer la valeur par défaut de arg_name dans le décorateur (ligne 6)
- checker dans le décorateur que l'objet passé à la fonction qui correspond à arg_name est bel et bien un dataframe (singe-indexed, ou multi-indexed, à voir après -> remarque que l'appel à args[0].index devrait renvoyer une erreur direct). Même si on pourrait aussi imaginer que c'est les fonctions décorées qui sont chargées de faire ce check, ça me paraît tout à fait ok.

2024-02-22 14:21 UTC, ClementJeannesson commented on enda/decorators.py
> +                # break out of the loop
Oupsie, "break out of the function"

2024-02-22 14:22 UTC, ClementJeannesson commented on enda/decorators.py
> +                raise RuntimeError("Cannot use the function with a multiindex dataframe having "
Ouais, `ValueError` est en tout cas plus en phase avec le comportement du reste du code de enda.

2024-02-22 14:23 UTC, ClementJeannesson commented on enda/decorators.py
> +                    # it should be a pd.Series
yes, abus de langage.

2024-02-22 14:31 UTC, ClementJeannesson commented on tests/test_decorators.py
> +    def test_handle_series_as_datetimeindex_default_behaviour(self):
J'ai été lazy. 
Pour les docstrings, je les mettais voloontairement pas, parce que ça s'affiche pas joliment lorsqu'on fait tourner les tests en ligne de commande. 
A la réflexion, c'est sacrifier la clarté sur l'autel de l'esthétique, et c'est pas forcément une bonne idée. 
Je vais les mettre.

2024-02-22 14:35 UTC, ClementJeannesson commented on enda/decorators.py
> +            # turn result (supposed to be a datetimeindex else error) back to series
Hmm, disons que si tu codes une fonction et que tu indiques dans le décorateur return_input_type=True, alors oui, ça veut dire qu'elle doit retourner un datetimeindex, et que tu veux qu'elle retourne une série si tu lui passes une série. 
Si ta fonction renvoie autre chose qu'un datetimeindex, alors tu es censé indiquer return_input_type=False, et le fait de la décorer fait qu'elle acceptera ou bien une série ou un datetimeindex, mais renverra le type final (par exemple un timedelta).

2024-02-29 16:44 UTC, sylviodupin requested changes
Y'a des erreurs de linter mais je peux m'en occuper après dans ma PR vu qu'elles s'affichent pas chez toi

2024-02-29 16:44 UTC, sylviodupin commented on enda/resample.py
> +    def forward_fill_final_record(
Ajouter un moyen de donner une date de fin en dur plutôt qu'un gap

2024-02-29 16:44 UTC, sylviodupin commented on enda/timeseries.py
> +        # it should be next call:
Pourquoi rollback l'appel à `collapse_to_periods` ?

2024-03-01 16:35 UTC, sylviodupin approved these changes

2024-03-01 16:38 UTC, merged