[1867](calendar) Refacto calendar
enercoop/enda pull request #17
Opened 2024-03-20 17:37 UTC by ClementJeannesson

2024-03-25 10:15 UTC, sylviodupin requested changes
Des erreurs de Linter qui traînent et que j'ai la flemme de toute lister, mais en gros il manque des docstrings, il faut réorganiser les imports, et il y a des else en trop dans certaines fonctions

2024-03-25 10:15 UTC, sylviodupin commented on enda/feature_engineering/calendar.py
> +        raise NotImplementedError("Abstract method")
A priori pas besoin de raise une erreur pour une méthode abstraite

2024-03-25 10:15 UTC, sylviodupin commented on enda/feature_engineering/calendar.py
> +    def get_lockdown(country: str, years_list: list[int] = None):
Avant, cette méthode s'appelait `get_french_lockdown`. Est-ce qu'on la laisserait pas dans Calendar avec un message de déprécation qui renvoie vers FrenchCalendar.get_lockdown histoire de pas casser les scripts qui l'utilisait ?

2024-03-25 10:15 UTC, sylviodupin commented on enda/feature_engineering/calendar.py
> +    def get_number_school_areas_off(years_list=None) -> pd.DataFrame:
Avant, cette fonction était dans Calendar et s'appelait `get_school_holidays` : est-ce qu'on la remettrait pas dans Calendar avec un message de déprécation renvoie vers celle-ci ?

2024-03-25 16:16 UTC, ClementJeannesson commented on enda/feature_engineering/calendar.py
> +    def get_lockdown(country: str, years_list: list[int] = None):
Ah oui, je voulais le faire, mais j'ai zappé

2024-03-25 16:18 UTC, sylviodupin commented on enda/feature_engineering/calendar.py
> +        warnings.warn(
Plutot utiliser le décorateur ?

2024-03-26 13:32 UTC, sylviodupin approved these changes

2024-03-26 15:01 UTC, merged